apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  labels: 
    azure.workload.identity/use: true
  annotations: 
    azure.workload.identity/client-id: b309bbad-924d-4628-ba79-3b49a62646a6
