provider: azure
policy: sync
commonLabels:
  azure.workload.identity/use: "true"
serviceAccount:
  create: true
  name: external-dns
  annotations:
    azure.workload.identity/client-id: 404btest1-ba04-4933-bcea-7d002test136
  labels:
    azure.workload.identity/use: "true"
azure:
  secretName: external-dns-azure
