provider: azure
policy: sync
commonLabels:
  azure.workload.identity/use: "true"
serviceAccount:
  create: true
  name: external-dns
  annotations:
    secretName: external-dns-userid-azure
  labels:
    azure.workload.identity/use: "true"
azure:
  secretName: external-dns-azure
